### ISSUE TITLE
Version 1.0.0

### ISSUE THREAD

**Issue by simonseyock** [simonseyock/jsdoc-type-pratt-parser#38]
TODO:

- [x] missing typescript syntax: https://github.com/simonseyock/jsdoc-type-pratt-parser/issues/4 <- at least `{ key?: string }`
- [x] Document spread vs. rest: https://github.com/simonseyock/jsdoc-type-pratt-parser/issues/5
- [x] Rename types to make them more eslint friendly
- [x] Export traverse config for eslint ast
- [x] figure out if https://github.com/simonseyock/jsdoc-type-pratt-parser/issues/18 should be addressed
- [x] remove special chars from meta: https://github.com/simonseyock/jsdoc-type-pratt-parser/issues/39
- [x] configure main branch for stable releases via semantic-release
